### PR TITLE
update YAML exercise count

### PR DESCRIPTION
**Pull request by benmarwick**

### CODE REVIEW

**Comment by ErinBecker** [comment]
Thanks @benmarwick. The numbers associated with "teaching" and "exercises" in the YAML header for each episode are meant to reflect the number of minutes required for each of those activities in that episode, not the count. Anyone have an estimate for the number of minutes to teach this exercise?

**Comment by tracykteal** [comment]
This exercise takes about 20 minutes. Give the exercise, then give students 10 minutes to work on it, then take about 10 minutes to discuss with the class.

**Comment by ErinBecker** [comment]
Thanks @tracykteal and @benmarwick

**Comment by benmarwick** [comment]
Oops, sorry I didn't know that about duration rather than count, my mistake!

**Pull request merged**
