### PR TITLE
added data for quality assurance exercise

### PR DESCRIPTION
**Pull request by tracykteal**
Adds the spreadsheet for the exercise in 04-quality-control module. Addresses https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/220

### CODE REVIEW

**Comment by tracykteal** [comment]
Darn merge conflicts. I can work to resolve, but @hoytpr @lmichael107 does this generally look OK?

**Comment by hoytpr** [comment]
The Excel file survey_sorting_exercise.xlsx is not in the data folder.?

**Comment by hoytpr** [comment]
@tracykteal https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/data/survey_sorting_exercise.xlsx?raw=true)
Points to the lesson data folder? So survey_sorting_exercise.xlsx should be in that folder, but it's not?

**Comment by hoytpr** [comment]
@tracykteal 
The original file is at:
https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/**sorting-data**/data/survey_sorting_exercise.xlsx?raw=true

**Comment by lmichael107** [comment]
looks good to me, aside fro the conflict

**Comment by hoytpr** [comment]
@tracykteal @lmichael107 
The **original** link was to "survey_sorting_exercise.xls" maybe the .xlsx is causing conflict? Otherwise LPG.

**Pull request merged**
