### PR TITLE
Revision of the lesson

### PR DESCRIPTION
**Pull request by anenadic**
See https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/296 for discussion.

### CODE REVIEW

**Comment by hoytpr** [comment]
Hi @anenadic

**Comment by hoytpr** [comment]
Hi @anenadic I wanted to check back and let you know I'm not ignoring this. I've pulled your entire PR down to my local computer and was able to render it in a separate branch (the side-by-side comparison is easier for me). For this much re-writing would you be willing to let me (ask if we can) set this up under a development page with The Carpentries? That way we will have a public site for rendering and comparing, and can involve more of the community in feedback. I really appreciate the work you've done, and to be very clear this is great and resolves some of the issues with the lesson flow,

**Review by fmichonneau — COMMENTED** [review]
I have started to review this pull request but didn't go through it all. Overall it seems that it's a good overhaul but there are a few instances of demotivational language. I provided suggestions for the files I have reviewed.

**Comment by hoytpr** [comment]
Thanks François.  I'll go through your review shortly. Very much appreciated @fmichonneau

**Comment by tracykteal** [comment]
I also like these changes with @fmichonneau updates. These are pretty significant though, and it would be great to be able to do something like @hoytpr suggests, and work on them in a branch to finalize before merging for them to go live. @fmichonneau do you have an approach you would suggest?

**Comment by anenadic** [comment]
Hi! Just coming back to this after holidays. Thanks for working on this @hoytpr @fmichonneau! What is the current status - do you still want me to set this up on a new branch and then do a PR @hoytpr? I am also happy to give anyone access to my repo if that makes things easier given that @fmichonneau did some changes in the meantime.

**Comment by hoytpr** [comment]
Glad you have stayed with this @anenadic .

I have been recovering from illness and unable to contribute. Still sick but paying attention so I can help if possible.

**Pull request merged**
