### PR TITLE
Added full data citation as suggested in issue 207

### PR DESCRIPTION
**Pull request by copystar**
As suggested in https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/207

### CODE REVIEW

**Comment by copystar** [comment]
I'm part of instructor group: 2017-07-31-ttt-online

**Comment by ErinBecker** [comment]
Thanks @copystar!

**Comment by hoytpr** [comment]
Just for my education: This should be closed now, right? Who closes it? @agbeltran @ErinBecker @copystar ???

**Comment by ErinBecker** [comment]
Good question @hoytpr. GitHub will automatically close an issue if the PR opener says something like "Fixes #207" or "Closes #207". I'm not sure if my comment here will do the trick. If not, then the maintainer for this repo should close that issue next time they're going through issues.

**Pull request merged**
