### PR TITLE
Edit 'Cardinal Rules' list to include items 4 & 5

### PR DESCRIPTION
**Pull request by brymz**

### CODE REVIEW

**Comment by hlapp** [comment]
@brymz perhaps I'm not seeing this correctly, but it looks to me like all you're changing is the breaking up two lines into multiple ones. Did you mean to change something beyond only formatting?

**Comment by brymz** [comment]
> all you're changing is the breaking up two lines into multiple ones.

That's correct. The formatting should fix the issue of the markdown
rendering the 'Cardinal Rules' list improperly as a quote block of three
items and a following paragraph starting with "seems like one thing...",
including items four and five. The result should be a quote block with five
items.

> Did you mean to change something beyond only formatting?

Nope. Its a great list!

**Comment by hlapp** [comment]
I see. I think the more straightforward way to fix this would be to remove the leading spaces in each line. Would you mind changing your fix to that so it's more obvious what's happening?

**Comment by brymz** [comment]
> remove the leading spaces in each line.

I tested removing the leading space and the issue in markdown rendering
returns. You're right! It's not a straightforward fix, but one I've found
important for keeping markdown lists properly rendered on the wiki/git.io.
A hard return in a list stops the list, unless the new line is aligned with
the list indentation. Indenting the list is what sets it as a quote block.
In my test of alternates, a soft wrap gave the quote block a scroll bar,
hiding the tail of the text.

> Would you mind changing your fix to that so it's more obvious what's
happening?

I could not find a way to remove the white space and still address the
issue of proper rendering.

**Comment by hlapp** [comment]
> A hard return in a list stops the list, unless the new line is aligned with
> the list indentation. Indenting the list is what sets it as a quote block.

Perhaps I wasn't clear enough in my initial comment. Removing the indentation for the whole list is what I meant to suggest, not just for the lines you were changing. And if the indentation is removed for the whole list, wouldn't that mean each line is then also aligned with the list indentation?

**Comment by brymz** [comment]
Absolutely. Sorry for the confusion.
Indentation is removed for the whole list. Looks good.

**Pull request merged**
